'use client'

import { useState } from 'react'
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  Badge,
  Button,
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui'
import {
  HelpCircle,
  Radar,
  Users,
  Network,
  Scale,
  Boxes,
  Shield,
  Radio,
  ChevronRight,
  X,
} from 'lucide-react'

interface PipelinePhase {
  id: string
  name: string
  icon: any
  description: string
  whatYouSee: string[]
  whatItDoes: string
  inputFrom: string | null
  outputTo: string | null
  route: string
}

const PIPELINE_PHASES: PipelinePhase[] = [
  {
    id: 'perimeter',
    name: 'PERIMETER',
    icon: Radar,
    description: 'The outer ring - raw intelligence feeds',
    whatYouSee: [
      'Raw tweets from monitored accounts',
      'YouTube videos from tracked channels',
      'RSS feed items',
      'Engagement metrics (likes, retweets, views)',
    ],
    whatItDoes:
      'Collects raw content from Twitter, YouTube, and RSS feeds. This is unprocessed data - just pulling in what people are saying.',
    inputFrom: null,
    outputTo: 'EXTRACTION',
    route: '/perimeter',
  },
  {
    id: 'tribunal',
    name: 'TRIBUNAL',
    icon: Users,
    description: 'Source approval/rejection',
    whatYouSee: [
      'Nominated sources (Twitter accounts, YouTube channels)',
      'Preliminary credibility scores',
      'Discovery context (how we found them)',
      'Approve/Reject buttons',
    ],
    whatItDoes:
      'When the system discovers new accounts that seem relevant, they get nominated here. You review them and decide if they should become trusted sources. This is NOT for stories - it\'s for SOURCES.',
    inputFrom: 'PERIMETER',
    outputTo: 'Approved sources feed PERIMETER',
    route: '/tribunal',
  },
  {
    id: 'extraction',
    name: 'EXTRACTION',
    icon: Network,
    description: 'Entity & claim extraction',
    whatYouSee: [
      'Entities: People, events, organizations mentioned',
      'Claims: Statements people are making',
      'Sentiment: Is discussion positive/negative?',
      'Context: The tweets driving each sentiment',
    ],
    whatItDoes:
      'AI analyzes raw content to extract WHO is being discussed, WHAT claims are being made, and HOW people feel about them. Click an entity to see the specific tweets that contribute to its sentiment.',
    inputFrom: 'PERIMETER',
    outputTo: 'AUDIT',
    route: '/extraction',
  },
  {
    id: 'audit',
    name: 'AUDIT',
    icon: Scale,
    description: 'Consensus & credibility scoring',
    whatYouSee: [
      'Consensus scores: How much agreement is there?',
      'Contention scores: How divisive is the topic?',
      'Source credibility breakdown',
      'Supporting vs denying sources',
    ],
    whatItDoes:
      'Calculates how much people agree or disagree on claims. High consensus = most sources agree. High contention = topic is divisive (good for debate shows!).',
    inputFrom: 'EXTRACTION',
    outputTo: 'NEXUS',
    route: '/audit',
  },
  {
    id: 'nexus',
    name: 'NEXUS',
    icon: Boxes,
    description: 'Story threading & opportunities',
    whatYouSee: [
      'Story threads: Connected claims grouped together',
      'Production opportunities: What shows could be made',
      'Suggested formats: News, debate, narrative, etc.',
      'Story strength scores',
    ],
    whatItDoes:
      'Connects related entities and claims into coherent story threads. Identifies what\'s newsworthy and suggests the best format for each story opportunity.',
    inputFrom: 'AUDIT',
    outputTo: 'SANCTION',
    route: '/nexus',
  },
  {
    id: 'sanction',
    name: 'SANCTION',
    icon: Shield,
    description: 'Story approval & assignment',
    whatYouSee: [
      'Pending stories ready for approval',
      'Producer assignment options',
      'Host selection for each format',
      'Final review before production',
    ],
    whatItDoes:
      'Where you approve story threads to become actual productions. Assign a Producer (who gathers info) and Hosts (who present it). This is the green light for content creation.',
    inputFrom: 'NEXUS',
    outputTo: 'SIGNAL',
    route: '/sanction',
  },
  {
    id: 'signal',
    name: 'SIGNAL',
    icon: Radio,
    description: 'Final output & publishing',
    whatYouSee: [
      'Completed show scripts',
      'Ready-to-publish content',
      'TTS audio generation status',
      'Publishing controls',
    ],
    whatItDoes:
      'The final output. Approved stories become fully-formed content with scripts generated by the assigned Host personality. Ready for TTS voice generation and publishing.',
    inputFrom: 'SANCTION',
    outputTo: null,
    route: '/signal',
  },
]

export function PipelineGuide({ compact = false }: { compact?: boolean }) {
  const [dialogOpen, setDialogOpen] = useState(false)
  const [selectedPhase, setSelectedPhase] = useState<PipelinePhase | null>(null)

  const showPhaseDetails = (phase: PipelinePhase) => {
    setSelectedPhase(phase)
    setDialogOpen(true)
  }

  if (compact) {
    return (
      <div className="flex items-center gap-2">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => setDialogOpen(true)}
          className="gap-1"
        >
          <HelpCircle className="h-4 w-4" />
          How does this work?
        </Button>

        <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
          <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <HelpCircle className="h-5 w-5" />
                Talk Show Go Pipeline
              </DialogTitle>
              <DialogDescription>
                How raw social media content becomes polished shows
              </DialogDescription>
            </DialogHeader>

            <div className="space-y-4 mt-4">
              {/* Flow visualization */}
              <div className="flex flex-wrap items-center justify-center gap-2 p-4 bg-muted border-2 border-foreground">
                {PIPELINE_PHASES.map((phase, idx) => {
                  const Icon = phase.icon
                  return (
                    <div key={phase.id} className="flex items-center gap-2">
                      <button
                        onClick={() => showPhaseDetails(phase)}
                        className="flex flex-col items-center p-2 hover:bg-background/50 rounded transition-colors"
                      >
                        <Icon className="h-5 w-5 mb-1" />
                        <span className="text-xs font-semibold">{phase.name}</span>
                      </button>
                      {idx < PIPELINE_PHASES.length - 1 && (
                        <ChevronRight className="h-4 w-4 text-muted-foreground" />
                      )}
                    </div>
                  )
                })}
              </div>

              {/* Phase list */}
              <div className="space-y-3">
                {PIPELINE_PHASES.map((phase) => {
                  const Icon = phase.icon
                  return (
                    <button
                      key={phase.id}
                      onClick={() => showPhaseDetails(phase)}
                      className="w-full text-left p-3 border-2 border-foreground/20 hover:border-foreground transition-colors flex items-start gap-3"
                    >
                      <Icon className="h-5 w-5 mt-0.5" />
                      <div className="flex-1">
                        <p className="font-semibold">{phase.name}</p>
                        <p className="text-sm text-muted-foreground">{phase.description}</p>
                      </div>
                      <ChevronRight className="h-5 w-5 text-muted-foreground" />
                    </button>
                  )
                })}
              </div>
            </div>
          </DialogContent>
        </Dialog>

        {/* Phase Details Dialog */}
        <Dialog
          open={dialogOpen && selectedPhase !== null}
          onOpenChange={(open) => {
            if (!open) setSelectedPhase(null)
          }}
        >
          {selectedPhase && (
            <DialogContent className="max-w-lg">
              <DialogHeader>
                <DialogTitle className="flex items-center gap-2">
                  {(() => {
                    const Icon = selectedPhase.icon
                    return <Icon className="h-5 w-5" />
                  })()}
                  {selectedPhase.name}
                </DialogTitle>
                <DialogDescription>{selectedPhase.description}</DialogDescription>
              </DialogHeader>

              <div className="space-y-4">
                <div>
                  <h4 className="font-semibold mb-2">What This Page Does</h4>
                  <p className="text-sm">{selectedPhase.whatItDoes}</p>
                </div>

                <div>
                  <h4 className="font-semibold mb-2">What You'll See</h4>
                  <ul className="space-y-1 text-sm">
                    {selectedPhase.whatYouSee.map((item, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <span className="text-primary">•</span>
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="flex gap-4 text-sm">
                  {selectedPhase.inputFrom && (
                    <div>
                      <span className="text-muted-foreground">Input from:</span>{' '}
                      <Badge variant="outline">{selectedPhase.inputFrom}</Badge>
                    </div>
                  )}
                  {selectedPhase.outputTo && (
                    <div>
                      <span className="text-muted-foreground">Output to:</span>{' '}
                      <Badge variant="outline">{selectedPhase.outputTo}</Badge>
                    </div>
                  )}
                </div>

                <Button
                  className="w-full"
                  onClick={() => {
                    window.location.href = selectedPhase.route
                  }}
                >
                  Go to {selectedPhase.name}
                </Button>
              </div>
            </DialogContent>
          )}
        </Dialog>
      </div>
    )
  }

  // Full guide view
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <HelpCircle className="h-5 w-5" />
          Pipeline Guide
        </CardTitle>
      </CardHeader>
      <CardContent>
        <p className="text-muted-foreground mb-4">
          Talk Show Go uses a 7-phase pipeline to transform raw social media chatter into
          polished content. Click any phase to learn more.
        </p>

        {/* Flow visualization */}
        <div className="flex flex-wrap items-center justify-center gap-2 p-4 bg-muted border-2 border-foreground mb-4">
          {PIPELINE_PHASES.map((phase, idx) => {
            const Icon = phase.icon
            return (
              <div key={phase.id} className="flex items-center gap-2">
                <button
                  onClick={() => showPhaseDetails(phase)}
                  className="flex flex-col items-center p-3 hover:bg-background/50 rounded transition-colors"
                >
                  <div className="p-2 border-2 border-foreground bg-background mb-1">
                    <Icon className="h-6 w-6" />
                  </div>
                  <span className="text-sm font-semibold">{phase.name}</span>
                </button>
                {idx < PIPELINE_PHASES.length - 1 && (
                  <ChevronRight className="h-5 w-5 text-muted-foreground" />
                )}
              </div>
            )
          })}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {PIPELINE_PHASES.map((phase) => {
            const Icon = phase.icon
            return (
              <button
                key={phase.id}
                onClick={() => showPhaseDetails(phase)}
                className="text-left p-3 border-2 border-foreground/20 hover:border-foreground transition-colors flex items-start gap-3"
              >
                <div className="p-2 border-2 border-foreground bg-muted">
                  <Icon className="h-5 w-5" />
                </div>
                <div className="flex-1">
                  <p className="font-semibold">{phase.name}</p>
                  <p className="text-sm text-muted-foreground">{phase.description}</p>
                </div>
              </button>
            )
          })}
        </div>

        {/* Phase Details Dialog */}
        <Dialog open={selectedPhase !== null} onOpenChange={(open) => !open && setSelectedPhase(null)}>
          {selectedPhase && (
            <DialogContent className="max-w-lg">
              <DialogHeader>
                <DialogTitle className="flex items-center gap-2">
                  {(() => {
                    const Icon = selectedPhase.icon
                    return <Icon className="h-5 w-5" />
                  })()}
                  {selectedPhase.name}
                </DialogTitle>
                <DialogDescription>{selectedPhase.description}</DialogDescription>
              </DialogHeader>

              <div className="space-y-4">
                <div>
                  <h4 className="font-semibold mb-2">What This Page Does</h4>
                  <p className="text-sm">{selectedPhase.whatItDoes}</p>
                </div>

                <div>
                  <h4 className="font-semibold mb-2">What You'll See</h4>
                  <ul className="space-y-1 text-sm">
                    {selectedPhase.whatYouSee.map((item, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <span className="text-primary">•</span>
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="flex gap-4 text-sm">
                  {selectedPhase.inputFrom && (
                    <div>
                      <span className="text-muted-foreground">Input from:</span>{' '}
                      <Badge variant="outline">{selectedPhase.inputFrom}</Badge>
                    </div>
                  )}
                  {selectedPhase.outputTo && (
                    <div>
                      <span className="text-muted-foreground">Output to:</span>{' '}
                      <Badge variant="outline">{selectedPhase.outputTo}</Badge>
                    </div>
                  )}
                </div>

                <Button
                  className="w-full"
                  onClick={() => {
                    window.location.href = selectedPhase.route
                  }}
                >
                  Go to {selectedPhase.name}
                </Button>
              </div>
            </DialogContent>
          )}
        </Dialog>
      </CardContent>
    </Card>
  )
}

export default PipelineGuide
